# Generated by Django 2.2.2 on 2019-10-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='branch',
            new_name='user_type',
        ),
    ]
