# Generated by Django 2.2.2 on 2019-10-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191021_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aadhar',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
