# Generated by Django 2.2.2 on 2019-10-21 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('Software', 'Software'), ('Hardware', 'Hardware')], max_length=30, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('theme', models.CharField(blank=True, max_length=50, null=True)),
                ('complexity', models.CharField(blank=True, choices=[('Simple', 'Simple'), ('Medium', 'Medium'), ('Complex', 'Complex')], max_length=30, null=True)),
                ('org_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('doc', models.FileField(upload_to='docs/')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackApp.Problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Student')),
            ],
        ),
    ]
