# Generated by Django 2.2.2 on 2019-10-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='category',
            field=models.CharField(blank=True, choices=[('Software', 'Software'), ('Hardware', 'Hardware'), ('Both', 'Both')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='org_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='theme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
