# Generated by Django 2.2.2 on 2019-10-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackApp', '0002_auto_20191026_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='discipline',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='outcome',
            field=models.TextField(blank=True, null=True),
        ),
    ]
