# Generated by Django 2.2.2 on 2019-10-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackApp', '0003_auto_20191026_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
